name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn@1.22.17

      - name: Install and Build
        run: |
          yarn
          yarn run build
          yarn link
          yarn --cwd ./demo
          yarn --cwd ./demo link sexy-qr
          yarn --cwd ./demo run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: demo/build
